# Generated by Django 3.0.6 on 2020-07-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathways',
            old_name='classes',
            new_name='class_1',
        ),
        migrations.AddField(
            model_name='courses',
            name='class_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class2', to='api.Pathways'),
        ),
        migrations.AddField(
            model_name='courses',
            name='class_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class3', to='api.Pathways'),
        ),
    ]
