# Generated by Django 3.0.6 on 2020-08-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200708_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('class_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class1', to='api.Course')),
                ('class_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class2', to='api.Course')),
                ('class_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class3', to='api.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='pathways',
            name='class_1',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Pathways',
        ),
        migrations.AddField(
            model_name='course',
            name='Pathways',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Pathways', to='api.Pathway'),
        ),
    ]
