# Generated by Django 3.1.5 on 2021-02-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('ID', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('HI', models.IntegerField(default=0)),
                ('CI', models.IntegerField(default=0)),
                ('DI', models.IntegerField(default=0)),
                ('fall', models.IntegerField(default=0)),
                ('spring', models.IntegerField(default=0)),
                ('summer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathName', models.CharField(blank=True, max_length=150)),
                ('relatedCourses', models.ManyToManyField(related_name='Pathways', to='database.Course')),
            ],
        ),
    ]
