# Generated by Django 3.1.5 on 2021-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210224_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='pathDescript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
