# Generated by Django 3.1.5 on 2021-02-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210225_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='pathDescript',
        ),
    ]
