# Generated by Django 3.1.5 on 2021-04-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('ID', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('HI', models.IntegerField(default=0)),
                ('CI', models.IntegerField(default=0)),
                ('DI', models.IntegerField(default=0)),
                ('major_retrictive', models.IntegerField(default=0)),
                ('fall', models.IntegerField(default=0)),
                ('spring', models.IntegerField(default=0)),
                ('summer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathName', models.CharField(max_length=150)),
                ('pathDescript', models.TextField(default='description')),
                ('priority1', models.ManyToManyField(related_name='priority1', to='database.Course')),
                ('priority2', models.ManyToManyField(related_name='priority2', to='database.Course')),
                ('priority3', models.ManyToManyField(related_name='priority3', to='database.Course')),
            ],
        ),
    ]
