# Generated by Django 3.1.5 on 2021-02-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='pathways',
            new_name='pathwaysArray',
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathName', models.CharField(blank=True, max_length=150)),
                ('relatedCourses', models.ManyToManyField(related_name='pathways', to='database.Course')),
            ],
        ),
    ]
