# Generated by Django 3.1.5 on 2021-02-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
        migrations.CreateModel(
            name='Pathways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_name', models.TextField()),
                ('courses', models.ManyToManyField(to='database.Classes')),
            ],
        ),
    ]
