# Generated by Django 3.1.5 on 2021-02-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210222_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='relatedCourses',
            field=models.ManyToManyField(to='database.Course'),
        ),
    ]
