# Generated by Django 3.1.5 on 2021-02-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210224_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='relatedCourses',
            field=models.ManyToManyField(related_name='pathways', to='database.Course'),
        ),
    ]
