# Generated by Django 3.1.5 on 2021-02-19 21:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210219_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='pathways',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
