# Generated by Django 3.1.5 on 2021-03-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20210321_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='relatedCourses',
        ),
    ]
