# Generated by Django 3.1.5 on 2021-03-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20210330_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major_retrictive',
            field=models.IntegerField(default=0),
        ),
    ]
